### ISSUE TITLE
Wireshark not properly displaying IPC message details 

### ISSUE THREAD

**Issue by ihack4falafel** [tomer8007/chromium-ipc-sniffer#10]
Hi there,

Not sure what I'm missing here but for whatever reason Wireshark is not displaying mojo IPC communication details as it supposed to based on your wiki examples. Here's screenshots for more details:

 
![Capture](https://user-images.githubusercontent.com/17316888/231198484-3fe3d834-7452-4474-b1be-91f637f55bcb.PNG)

![Capture2](https://user-images.githubusercontent.com/17316888/231198486-332fbabb-e654-473f-b7ea-b209d73e2ceb.PNG)

Your help is much appreciated!

**Comment by ihack4falafel** [comment]
Looks like it.. it worked for me as soon as I used Chromium v109.0.5414.120. Any plans to support IPCZ in the near future?

![Capture](https://user-images.githubusercontent.com/17316888/231230820-95866d16-8a69-454e-a79e-9c2a274ee13c.PNG)

**Comment by ihack4falafel** [comment]
Fair enough and looking forward to it. Great tool btw!

**Comment by tomer8007** [comment]
@ihack4falafel You can disable IPCZ by running chrome.exe with the following arguments:
`--disable-features=MojoIpcz`
This way you don't have to use an older chrome version.
