### ISSUE TITLE
Error occurs when open devtools in chrome.

### ISSUE THREAD

**Issue by shenzhigang** [tomer8007/chromium-ipc-sniffer#4]
Chrome version: 92.0.4515.159 (Official Build) (32-bit)
Platform: windows 10 64bit
An error dialog box shows 'frame 1482 too long' when open devtools in chrome, and after this, no more communications were captured.

![image](https://user-images.githubusercontent.com/8005935/132282349-100ff8b8-4793-4bf8-84ae-7ad881598b1a.png)

**Comment by tomer8007** [comment]
@shenzhigang Please try v0.5.3. Large packetes are now truncated.
e.g when opening devtools the renderer's [JavaScriptExecutionRequest ](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/frame/frame.mojom;l=742;drc=7a0b88f6d5c015fd3c280b58c7a99d8e1dca28ac) looks like this:

![image](https://user-images.githubusercontent.com/11458759/133956864-6fff2ce2-333b-459f-b817-6e218b911ace.png)

This is calling `DevToolsAPI.dispatchMessage`.

**Comment by shenzhigang** [comment]
> @shenzhigang Please try v0.5.3. Large packetes are now truncated.
> e.g when opening devtools the renderer's [JavaScriptExecutionRequest ](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/public/mojom/frame/frame.mojom;l=742;drc=7a0b88f6d5c015fd3c280b58c7a99d8e1dca28ac) looks like this:
> 
> ![image](https://user-images.githubusercontent.com/11458759/133956864-6fff2ce2-333b-459f-b817-6e218b911ace.png)
> 
> This is calling `DevToolsAPI.dispatchMessage`.

It works on version 0.5.3. Thanks.
