### ISSUE TITLE
 Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified

### ISSUE THREAD

**Issue by SpiralBL0CK** [tomer8007/chromium-ipc-sniffer#7]
For some reason wireshark won't open any ideea?
Here is what i get 
[+] Starting up
[+] Determining your chromium version
[+] You are using chromium 96.0.4664.110
[+] Checking mojom interfaces information
[+] Checking legacy IPC interfaces information
[!] Cached info is for 94.0.4606.61, you may run --update-interfaces-info
[+] Extracting scrambled message names from chrome.dll...
[+] Copying LUA dissectors to Wirehsark plugins directory
[!] Could not find Wireshark's colorfilters file, skipping color configuration
[+] Enumerating existing chrome pipes
[+] Starting sniffing of chrome named pipe to \\.\pipe\chromeipc.
[+] Opening Wirehark

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at ChromiumIPCSniffer.Program.Main(String[] args)

**Comment by tomer8007** [comment]
Well, the program tries to
https://github.com/tomer8007/chromium-ipc-sniffer/blob/fb007b09c87e25735e5b0220a43573445a92b74f/Chrome%20IPC%20Sniffer/Main.cs#L88
Where is your Wireshark installed?

**Comment by SpiralBL0CK** [comment]
probably somewhere else not in program files
i will take a look and solve it out thx for pointing me that

**Comment by SpiralBL0CK** [comment]
yep change the directory and works like a charm! i do have another question is there any way i could like tell the sniffer for which chrome to sniff eg sniff after i start chromium from debugger not the chrome i have opened
